<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle-01-numpy-and-matplotlib-iris-Anam-Ayoub/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom : ANAM Ayoub
Filière : SIIA
Année universitaire : 2025/2026

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# **Partie A — Importation du Dataset, Arrays, Premières Manipulations**

### **A1. Importation du dataset**
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [2]:
# Votre code ici
#=========== BLOC 1 ===========

# Pour importer NumPy
import numpy as np

# Pour importer Matplotlib
import matplotlib as mlp

# Stockage des données
data = np.genfromtxt('Iris.csv', delimiter=',', dtype=str, skip_header=1)

# Affichage de 'shape'
np.shape(data)

(150, 6)

### **A2. Séparation des features et des espèces**
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [3]:
# Votre code ici
#=========== BLOC 2 ===========

# L'extraction des 4 premières colonnes dans features
# Nous avons commencé par la colonne 1, car la colonne 0 ne contient que les ID
# astype(float) pour transformer les données en flottant
features = data[: , 1:5].astype(float)

# L'extraction de la dernière colonne dans species
species = data[: , -1]

### **A3. Indexing**
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [4]:
# Votre code ici
#=========== BLOC 3 ===========

print(features[:5 , :])
# :5 indique que nous voulons les 5 premières lignes (indices 0 à 4)
# : indique que nous voulons toutes les colonnes


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### **A4. Extraction d’une colonne**
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [5]:
# Votre code ici
#=========== BLOC 4 ===========

sepal_length = features[: , 0]
# : indique que nous voulons toutes les lignes
# 0 s'est l'indice de la première colonne

print(f"Size: {np.size(sepal_length)}\ndtype: {sepal_length.dtype}")

Size: 150
dtype: float64


### **A5. Slicing par espèce**
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [6]:
# Votre code ici
#=========== BLOC 5 ===========

setosa_features = features[:50 , :]
# :50 pour extraire les 50 premières lignes (indices 0 à 49)


# **Partie B — Statistiques Basiques et Opérations Mathématiques**

### **B6. Moyenne par colonne**
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [7]:
# Votre code ici
#=========== BLOC 6 ===========

moy_col_features = np.mean(features, axis=0)

print(moy_col_features)

[5.84333333 3.054      3.75866667 1.19866667]


### **B7. Min et Max**
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [8]:
# Votre code ici
#=========== BLOC 7 ===========

min_petal_length = np.min(features[:,2])
max_petal_length = np.max(features[:,2])
# la longueur des pétales se trouve dans la troisième colonne (indice 2)

print(f"Valeur minimale: {min_petal_length}\nValeur maximale: {max_petal_length}")

Valeur minimale: 1.0
Valeur maximale: 6.9


### **B8. Normalisation**
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [9]:
# Votre code ici
#=========== BLOC 8 ===========

normalized_petals = np.divide(features[: , 2] , max_petal_length)

print(normalized_petals[:5])

[0.20289855 0.20289855 0.1884058  0.2173913  0.20289855]


### **B9. Somme cumulée (Versicolor)**
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [10]:
# Votre code ici
#=========== BLOC 9 ===========

somme_Versicolor = np.cumsum(features[50:100 , 3])
# [50:100] est utilisé car la classe Versicolor se trouve entre les indices 50 et 99
# (soit de la 51ème à la 100ème ligne)

print(somme_Versicolor[:10])



[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


### **B10. Somme cumulée (Verginica)**
Calculez la somme cumulée des longeurs des pétales pour Virginica.
Affichez les 10 premières valeurs.


In [11]:
# Votre code ici
#=========== BLOC 10 ===========

somme_Verginica = np.cumsum(features[100: , 2])
# [100:] est utilisé car la classe Virginica se trouve à partir de l'indice 100
# (soit de la 101ème ligne à la fin)

print(somme_Verginica[:10])


[ 6.  11.1 17.  22.6 28.4 35.  39.5 45.8 51.6 57.7]


# **Partie C — Transformations Avancées avec NumPy**

### **C11. Espèces uniques**
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [12]:
# Votre code ici
#=========== BLOC 11 ===========

unique_species, counts = np.unique(species, return_counts=True)
# np.unique extrait les valeurs uniques de 'species' et les stocke dans 'unique_species'
# return_counts=True permet de stocker le nombre d'occurrences de chaque espèce dans 'counts'

print("Espèces uniques et leurs occurrences:")

for s,c in zip(unique_species, counts):
  print(f"{s} --> {c}")



Espèces uniques et leurs occurrences:
Iris-setosa --> 50
Iris-versicolor --> 50
Iris-virginica --> 50


### **C12. Reshape par espèce**
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [13]:
# Votre code ici
#=========== BLOC 12 ===========

features_by_species = features.reshape(3, 50, 4)
# Redimensionne 'features' en un tenseur de 3 dimensions
# 3 espèces, 50 échantillons(50 lignes), 4 caractéristiques(4 colonnes)

print(f"class1 :\n{features_by_species[0 , :3 , :]}\n")
print(f"class2 :\n{features_by_species[1 , :3 , :]}\n")
print(f"class3 :\n{features_by_species[2 , :3 , :]}")


class1 :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

class2 :
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]]

class3 :
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]]


### **C13. Concaténation**
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [14]:
# Votre code ici
#=========== BLOC 13 ===========

cat = np.concatenate((moy_col_features , np.zeros(4)))
print(f"Colonne concaténée:\n{cat}")


Colonne concaténée:
[5.84333333 3.054      3.75866667 1.19866667 0.         0.
 0.         0.        ]


### **C14. Data cleaning (simulation)**
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [41]:
# Votre code ici
#=========== BLOC 14 ===========

# Créons une copie de 'features' pour simuler des NaNs sans altérer l'original
copy_features = features.copy()

# Insérons quelques NaNs à des positions spécifiques pour la simulation
copy_features[0, 0] = np.nan # Première ligne, première colonne
copy_features[5, 2] = np.nan # Sixième ligne, troisième colonne
copy_features[10:12, 1] = np.nan # Lignes 10 et 11, deuxième colonne

print("Array avec NaNs simulés (premières 12 lignes):")
print(copy_features[:12])

cleaned_features = np.nan_to_num(copy_features)
# NaN est remplacé par la valeur par defaut (0)

print("\nArray avec NaNs remplacés (premières 12 lignes):")
print(cleaned_features[:12])


Array avec NaNs simulés (premières 12 lignes):
[[nan 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 nan 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 nan 1.5 0.2]
 [4.8 nan 1.6 0.2]]

Array avec NaNs remplacés (premières 12 lignes):
[[0.  3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 0.  0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 0.  1.5 0.2]
 [4.8 0.  1.6 0.2]]


### **C15. Broadcasting**
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [17]:
# Votre code ici


### **C16. np.where**
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [18]:
# Votre code ici


# **Partie D — Visualisation avec Matplotlib (Plots Simples)**

### **D17. Line plot**
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [19]:
# Votre code ici


### **D18. Scatter plot**
Scatter plot : longueur vs largeur des pétales.


In [20]:
# Votre code ici


### **D19. Bar chart**
Bar chart des moyennes des quatre caractéristiques.


In [21]:
# Votre code ici


### **D20. Histogram**
Histogramme de la largeur des sépales (10 bins).


In [22]:
# Votre code ici


### **D21. Boxplot par espèce**
Boxplot des longueurs des pétales par espèce.


In [23]:
# Votre code ici


# **Partie E — Visualisations Avancées**

### **E22. Subplots comparatifs**
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [24]:
# Votre code ici


### **E23. Grille 2x2**
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [25]:
# Votre code ici


### **E24. Bar chart avec error bars**
Moyennes par espèce avec écart-type.


In [26]:
# Votre code ici


### **E25. Scatter coloré par espèce**
Scatter plot avec couleurs par espèce.


In [27]:
# Votre code ici


### **E26. Line plot superposé**
Cumsum des largeurs des pétales par espèce.


In [28]:
# Votre code ici


# **Partie F — Mini-Analyse Finale**

### **F27. Corrélations**
Calculez la matrice de corrélation avec `np.corrcoef`.


In [29]:
# Votre code ici


### **F28. Visualisation des corrélations**
Visualisez les corrélations sous forme de bar chart ou scatter.


In [30]:
# Votre code ici


### **F29. Variance par espèce**
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [31]:
# Votre code ici


### **F30. Conclusion**
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...